---
title: "ecg_visual_EDA"
format: html
execute: 
  echo: true
---

# Setup and Global Preprocessing

```{r}
#| label: setup-and-global-preprocessing
#| message: false
#| warning: false

# ---Package Instalation ---
# List of required packages
required_packages <- c("tidyverse", "patchwork")

# Automatic installer for missing dependencies
new_packages <- required_packages[!(required_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)

library(tidyverse)
library(patchwork)

# --- Initial setup ---
# Define colors for further use to achieve consistency
colors <- c(
  "Normal"           = "#4a4b4c",
  "Arrhythmia"       = "#d73027",
  "Normal Reference" = "#b3b4b5"
)

# Set a seed to ensure that the 'random' selections are the same every time
set.seed(20)

# --- Data Ingestion ---
# Directly reading from the compressed ZIP archive
zip_path <- "../data/mitbih_train.zip"
ecg_raw <- read_csv(unz(zip_path, "mitbih_train.csv"), col_names = FALSE)

# Assigning structured column names: 't1' through 't187' for temporal points, and 'label' for the cardiological classification
colnames(ecg_raw) <- c(paste0("t", 1:(ncol(ecg_raw) - 1)), "label")

# --- Labeling and Classification ---
ecg_tidy <- ecg_raw %>% 
  mutate(
    sample_id = row_number(),
    label_name = case_when(
      label == 0 ~ "Normal",
      label == 1 ~ "Supraventricular",
      label == 2 ~ "Ventricular",
      label == 3 ~ "Fusion",
      label == 4 ~ "Unclassified"
    ),
    # Ordering factors to ensure 'Normal' is always the baseline in plots
    label_name = factor(label_name, levels = c("Normal", "Supraventricular", "Ventricular", "Fusion", "Unclassified")), 
    color_group = ifelse(label == 0, "Normal", "Arrhythmia")
  ) 


# Map colors to all existing labels in the dataset
# This ensures any arrhythmia class automatically gets the "Arrhythmia" color
all_detected_labels <- levels(ecg_tidy$label_name)

full_colors <- setNames(
  ifelse(all_detected_labels == "Normal",
         colors["Normal"],
         colors["Arrhythmia"]),
  all_detected_labels
  )

# --- Representative Sample Selection ---
# Extracting individual exemplar beats for each class 
selected_samples_long <- ecg_tidy %>% 
  group_by(label_name) %>% 
  slice_sample(n = 1) %>% 
  ungroup() %>% 
  pivot_longer(cols = starts_with("t"),names_to = "time", values_to = "amplitude") %>% 
  mutate(time = as.numeric(str_remove(time, "t")))

# --- Baseline Reference Extraction ---
# Isolationg a single, representative 'Normal' heart beat to serve as a morphological baseline for comparative visualization
normal_baseline <- selected_samples_long %>% 
  filter(label_name == "Normal") %>% 
  select(time, baseline_amp = amplitude)

# --- Statistical Aggregation ---
# Calculating mean and standard deviation per time points across all classes.
# This serves as the foundation for statistical uncertainty ribbons
ecg_stats <- ecg_tidy %>%
  slice_sample(prop = 0.2) %>% 
  pivot_longer(cols = starts_with("t"), names_to = "time", values_to = "amp") %>% 
  mutate(time = as.numeric(str_remove(time, "t"))) %>% 
  group_by(label_name, color_group, time) %>% 
  summarise(
    mean_amp = mean(amp, na.rm = TRUE),
    sd_amp   = sd(amp, na.rm = TRUE),
    .groups  = "drop"
  )
```

# Dataset Representative Dashboard

```{r}
#| label: fig-representative-dashboard
#| fig-height: 10
#| fig-width: 16
#| message: false

# --- Local Preprocessing - comparative analysis ---
# Join with baseline and ensure factor levels
plot_data_rep <- selected_samples_long %>% 
  filter(label_name != "Normal") %>% 
  left_join(normal_baseline, by = "time") %>% 
  mutate(label_name = factor(label_name,
                             levels = c("Supraventricular", "Ventricular", "Fusion", "Unclassified")))

# --- Plotting - comparative analysis---
p_morphology <- ggplot(plot_data_rep, aes(x = time)) +
  # Background reference
  geom_line(aes(y = baseline_amp, color = "Normal Reference"), linetype = "dashed", linewidth = 0.5) +
  # Main signal
  geom_line(aes(y = amplitude, color = "Arrhythmia"),
            linewidth = 0.8) +
  
  facet_wrap(~label_name, ncol = 1, scales = "free_y") +
  scale_color_manual(values = colors) +

  labs(
    title = "Representative Pathological Beat Morphology",
    subtitle = "Comparative analysis of individual arrhythmia samples against a 'Normal' reference baseline",
    x = "Time Index (t)",
    y = "Amplitude (mV)",
    color = "Clinical Category",
    caption = "(Fig. 1) The complex shapes and temporal shifts in pathological beats suggest that classical ML methods could be insufficient."
  ) +
  # Styling the plot
  theme_minimal(base_size = 11) + 
  theme(
    legend.position = "bottom",
    plot.title = element_text(face = "bold", size = 16),
    strip.background = element_rect(fill = "grey95", color = NA),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank(),
    panel.spacing = unit(1, "lines"),
    plot.caption = element_text(size = 10, hjust = 0, face = "italic", margin = margin(t = 10))
  )

# --- Local Preprocessing - bar plots ---
pathology_dist <- ecg_tidy %>%
  # Exclude 'Normal' class to avoid it dominating others
  filter(label_name != "Normal") %>% 
  count(label_name, color_group) %>% 
  mutate(percent_of_pathologies = n / sum(n) * 100) %>% 
  mutate(label_name = factor(label_name, 
                             levels = c("Supraventricular", "Ventricular", "Fusion", "Unclassified")))

# --- Plotting - bar plots ---
p_dist <- ggplot(pathology_dist, aes(x = label_name, y = n, fill = label_name)) +
  geom_col(fill = colors["Arrhythmia"], alpha = 0.8, width = 0.6) +
  geom_text(aes(label = paste0(round(percent_of_pathologies, 1), "%\nof anomalies")), vjust = -0.5, size = 4, fontface = "bold") +
  # Add 15% padding at the top to ensure labels don't get clipped
  scale_y_continuous(expand = expansion(mult = c(0, 0.15)))+
  labs(
    title = "Detailed Distribution of Arrhythmia Classes",
    subtitle = "Analysis of pathological samples only to highlight minority class imbalances",
    x = "Arrhythmia Type",
    y = "Count",
    fill = "Type",
    caption = "(Fig. 2) Significant class imbalance could be a major challenge for model training, \nas it may lead to biased predictions."
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 16),
    panel.grid.minor = element_blank(),
    panel.spacing = unit(1, "lines"),
    plot.caption = element_text(size = 10, hjust = 0, face = "italic", margin = margin(t = 10))
  )

p_repr <- (p_morphology + p_dist + plot_layout(widths = c(2, 1)) +
  plot_annotation(
    title = "Clinical Profile of Arrhythmia Classes",
    subtitle = "Integration of signal morphology and dataset prevalence",
    theme = theme(plot.title = element_text(face = "bold", size = 18))
  ))

p_repr
```

# Analysis of Variability Among Each Arrhythmia Class

```{r}
#| label: fig-analysis-of-variability-among-each-arrhythmia-class
#| fig-height: 10
#| fig-width: 8

# --- Local Preprocessing ---
pathology_stats <- ecg_stats %>% 
  filter(label_name != "Normal") %>% 
  mutate(label_name = factor(label_name,
                             levels = c("Supraventricular", "Ventricular", "Fusion", "Unclassified")))

# --- Plotting ---
rib_plot <- ggplot(pathology_stats, aes(x = time)) +
  # Range of variability (ribbon)
  geom_ribbon(aes(ymin = mean_amp - sd_amp,
                  ymax = mean_amp + sd_amp,
                  fill = "Arrhythmia"),
              alpha = 0.15) +
  # Main line
  geom_line(aes(y = mean_amp, color = "Arrhythmia"),
            linewidth = 1) +
  
  facet_wrap(~ label_name, ncol = 1, scales = "free_y") +
  scale_color_manual(values = colors) +
  
  labs(
    title = "Analysis of Variability Among Each Arrhythmia Class",
    subtitle = "Aggregated mean waveforms with +/-1 standard deviation variability",
    x = "Time Index (t)",
    y = "Amplitude (mV)",
    color = "Clinical Status",
    caption = "(Fig. 3) High variability wiithin ceratin classes suggests significant morphology overlap, which may make it difficult for \nany model to distinguish between them."
  ) +
  # Styling the plot
  theme_minimal(base_size = 11) + 
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 16),
    strip.background = element_rect(fill = "grey95", color = NA),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank(),
    panel.spacing = unit(1, "lines"),
    plot.caption = element_text(size = 10, hjust = 0, face = "italic", margin = margin(t = 10))
  )

rib_plot
```

# Signal Autocorrelation

```{r}
#| label: fig-acf
#| fig-width: 14
#| fig-height: 6
#| message: false
#| warning: false

# --- Local Preprocessing ---
acf_results <- selected_samples_long %>% 
  group_by(label_name) %>% 
  summarise(
    # Calculate correlation for lags from 0 to 50
    acf_values = list(as.numeric(acf(amplitude, lag.max = 50, plot = FALSE)$acf)),
    lag = list(0:50),
    .groups = "drop"
  ) %>% 
  unnest(cols = c(acf_values, lag))

# Plot on the left - Normal Rhythm
p_left <- acf_results %>% 
  filter(label_name == "Normal") %>% 
  ggplot(aes(x = lag, y = acf_values)) +
  geom_col(fill = full_colors["Normal"], width = 0.7) +
  labs(
    title = "Normal Beat Autocorrelation",
    subtitle = "Standard temporal decay signature",
    x = "Lag (Time steps)",
    y = "Autocorrelation",
    caption = "(Fig. 4) The Normal class has a specific temporal signature, showing \nhow the signal's rhythm changes quickly over time."
  ) +
  theme_minimal(base_size = 11) +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 16),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank(),
    panel.spacing = unit(1, "lines"),
    plot.caption = element_text(size = 10, hjust = 0, face = "italic", margin = margin(t = 10))
  )

# Plot on the right - Arrhythmias
p_right <- acf_results %>% 
  filter(label_name != "Normal") %>% 
  ggplot(aes(x = lag, y = acf_values, fill = label_name)) +
  geom_col(width = 0.7) +
  facet_wrap(~label_name, ncol = 2) +
  scale_fill_manual(values = full_colors) +
  labs(
    title = "Arrhythmia classes",
    subtitle = "Temporal structure differences across arrhythmia",
    x = "Lag (Time steps)",
    y = NULL,
    caption = "(Fig. 5) Each arrhythmia class has a different autocorrelation shape. These unique rhythms are hard for simple models to understand."
  ) +
  # Styling the plot
  theme_minimal(base_size = 11) + 
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 16),
    strip.background = element_rect(fill = "grey95", color = NA),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank(),
    panel.spacing = unit(1, "lines"),
    plot.caption = element_text(size = 10, hjust = 0, face = "italic", margin = margin(t = 10))
  )

acf_plots <- (p_left + p_right + plot_layout(widths = c(1, 1.8)))
acf_plots
```

# RMS Deviation Analysis

```{r}
#| label: fix-boxplot-rms
#| fig-width: 8
#| fig-height: 10
#| message: false
#| warning: false

# --- Local Preprocessing ---
# Calculate RMS deviation
rms_deviation <- ecg_tidy %>% 
  pivot_longer(
    cols = starts_with("t"),
    names_to = "time",
    values_to = "amp"
  ) %>% 
  mutate(time = as.numeric(str_remove(time, "t"))) %>% 
  left_join(
    ecg_stats %>% select(label_name, time, mean_amp),
    by = c("label_name", "time")
  ) %>% 
  mutate(dev = amp - mean_amp) %>% 
  group_by(sample_id, label_name) %>% 
  summarise(
    rms_dev = sqrt(mean(dev^2, na.rm = TRUE)),
    .groups = "drop"
  )

# Compute Y limits
y_min <- floor(min(rms_deviation$rms_dev, na.rm = TRUE) * 10) / 10
y_max <- ceiling(max(rms_deviation$rms_dev, na.rm = TRUE) * 10) / 10

# --- Plotting ---
# Left plot
p_normal <- rms_deviation %>% 
  filter(label_name == "Normal") %>% 
  ggplot(aes(x = "", y = rms_dev)) +
  geom_violin(fill = colors["Normal"], alpha = 0.7) +
  geom_boxplot(width = 0.18, outlier.shape = NA, alpha = 0.9) +
  labs(
    title = "Normal Rhythm",
    x = NULL,
    y = "RMS Deviation (mV)"
  ) + 
  coord_cartesian(ylim = c(y_min, y_max)) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(face = "bold", size = 14),
    panel.grid.minor = element_blank()
  )

# Right plot
p_arrhythmia <- rms_deviation %>% 
  filter(label_name != "Normal") %>% 
  mutate(
    label_name = factor(
      label_name,
      levels = c("Supraventricular", "Ventricular", "Fusion", "Unclassified")
    )
  ) %>% 
  ggplot(aes(x = "", y = rms_dev, fill = label_name)) +
  geom_violin(alpha = 0.7) +
  geom_boxplot(width = 0.18, outlier.shape = NA, alpha = 0.9) +
  facet_wrap(~ label_name, ncol = 2) +
  scale_fill_manual(values = full_colors) +
  labs(
    title = "Arrhythmia Classes",
    x = NULL,
    y = NULL
  ) +
  # Ensure each plot has the same y scale
  coord_cartesian(ylim= c(y_min, y_max)) + 
  theme_minimal(base_size = 11) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 14),
    strip.background = element_rect(fill = "grey95", color = NA),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

# Patchwork layout
rcs_plot <- (p_normal + p_arrhythmia + 
  plot_layout(widths = c(1, 2)) +
  plot_annotation(
    title = "Within-Class ECG Morphology Variability",
    subtitle = "RMS deviation from class-mean waveform",
    caption = "(Fig 6.) The contrast between the stable Normal class (left) and high variability of arrhythmias (right) suggests that \nBatch Normalization is needed to keep the model stable.",
    theme = theme(
      plot.title = element_text(face = "bold", size = 18),
      plot.subtitle = element_text(size = 12),
    plot.caption = element_text(size = 10, hjust = 0, face = "italic", margin = margin(t = 10))
  )
))

rcs_plot
```

# Export Plots

```{r}
ggsave("Fig_1_2_Morphology.pdf",
       plot = p_repr, width = 16, height = 10)

ggsave("Fig_3_Variability.pdf",
       plot = rib_plot, width = 10, height = 8)

ggsave("Fig_4_5_ACF.pdf",
       plot = acf_plots, width = 14, height = 6)

ggsave("Fig_6_RMS_Comparison.pdf",
       plot = rcs_plot, width = 8, height = 10)

```
